require('./callIdCounter');
require('./registerUnregisterHook');
require('./callsAllRegisteredHooks');
require('./singleHookReturnValues');
require('./callsCallbacksInOrder');
require('./respectPreviousCallsOption');
require('./handlesRejectedHooks');
require('./callbackApisMatch');
require('./jshint.spec.js');